#!/usr/bin/env bash
set -euo pipefail

# WinArc Wine bootstrap - Revision 7
#
# Revision 6 is the last verified server/client boundary baseline.
# Keep it pinned and execute it first; then add the native iPhoneOS ARM64
# ntdll Unix core gate without destabilising the already-passing path.
#
# Once the Wine path is complete this bootstrap will be flattened again into
# one self-contained implementation. There is still only one tracked Wine
# bootstrap file in WinArc.

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
WINE_ROOT="$ROOT/wine"
BUILD="$WINE_ROOT/build"
LOGS="$BUILD/logs"
GENERATED="$WINE_ROOT/generated"

REV6_COMMIT="f39dbcd7d7e745d271a5fb4f57e851723a892750"
JUICE_COMMIT="c0de19d93064eac25f87524849e12bb2d49e9a4f"
BOOTSTRAP_REVISION="7.1"
MIN_IOS="${WINARC_WINE_MIN_IOS:-14.0}"

die()
{
    echo "WINARC_WINE_BOOTSTRAP=FAIL"
    echo "ERROR=$*" >&2
    exit 1
}

log()
{
    printf '%s\n' "$*"
}

log "WINARC_COMPONENT=wine"
log "WINARC_WINE_BOOTSTRAP_REVISION=$BOOTSTRAP_REVISION"
log "WINARC_WINE_ROUTE=REV6_BASELINE_PLUS_NATIVE_NTDLL_UNIX"
log "WINARC_REV6_PIN=$REV6_COMMIT"

mkdir -p "$BUILD" "$LOGS" "$GENERATED"

# ---------------------------------------------------------------------------
# Gate 0: run the exact Revision 6 script that passed WinArc Run #9.
#
# It must be staged inside wine/, not wine/build/, because Revision 6 resolves
# the repository root relative to its own script location. Keeping the same
# directory depth preserves all verified paths exactly.
#
# Pinning by commit keeps all already-verified wineserver/client code byte-for-
# byte stable while Revision 7 works only on ntdll. Do not use HEAD^ here:
# user-side commits between revisions must not change the baseline.
# ---------------------------------------------------------------------------

REV6_SCRIPT="$WINE_ROOT/bootstrap-rev6.sh"

git fetch --quiet origin "$REV6_COMMIT"
git show "$REV6_COMMIT:wine/bootstrap-wine.sh" > "$REV6_SCRIPT"
chmod +x "$REV6_SCRIPT"

grep -Fq 'BOOTSTRAP_REVISION="6"' "$REV6_SCRIPT" || \
    die "pinned Revision 6 bootstrap marker missing"

bash "$REV6_SCRIPT" | tee "$LOGS/revision6-baseline.log"

grep -Fq "WINARC_WINE_BOOTSTRAP=PASS" "$LOGS/revision6-baseline.log" || \
    die "Revision 6 baseline did not pass"
grep -Fq "WINE_CLIENT_INPROCESS_BRIDGE_COMPILE=PASS" \
    "$LOGS/revision6-baseline.log" || \
    die "Revision 6 client bridge gate did not pass"

log "WINARC_REV6_BASELINE=PASS"

# Revision 6 cloned and pinned Juice for us.
JUICE_DIR="$WINE_ROOT/upstream/Juice"
WINE="$JUICE_DIR/wine"
HOST_BUILD="$BUILD/wine-host-tools"

test -d "$JUICE_DIR/.git" || die "Revision 6 did not prepare Juice"
actual="$(git -C "$JUICE_DIR" rev-parse HEAD)"
test "$actual" = "$JUICE_COMMIT" || \
    die "unexpected Juice commit after Revision 6: $actual"

test -f "$HOST_BUILD/include/config.h" || \
    die "Revision 6 host config.h missing"
test -f "$WINE/dlls/ntdll/unix/loader.c" || \
    die "Wine ntdll loader source missing"
test -f "$WINE/dlls/ntdll/unix/virtual.c" || \
    die "Wine ntdll virtual source missing"
test -f "$JUICE_DIR/toolchain/juice-ios-map-tryfixed.h" || \
    die "Juice iOS MAP_TRYFIXED adapter missing"

grep -Fq "__wine_main" "$WINE/dlls/ntdll/unix/loader.c" || \
    die "Wine __wine_main source entry missing"
grep -Fq "WINESERVERSOCKET" "$WINE/dlls/ntdll/unix/server.c" || \
    die "Wine WINESERVERSOCKET source contract missing"

log "WINE_NTDLL_SOURCE_CONTRACT=PASS"

# ---------------------------------------------------------------------------
# Gate 1: iOS ntdll compile overlay.
#
# The host build supplies Wine-generated headers/config. Individual ntdll Unix
# translation units are compiled directly with the physical iPhoneOS SDK.
# This is the same broad architecture proven by Madeira's iOS CI, but WinArc
# uses Juice's Wine/iOS source and its own isolation layer.
# ---------------------------------------------------------------------------

cat > "$GENERATED/winarc_ntdll_ios_config.h" <<'C_EOF'
#ifndef WINARC_NTDLL_IOS_CONFIG_H
#define WINARC_NTDLL_IOS_CONFIG_H

#include "config.h"

/*
 * The config header was generated by the macOS host-tools build. Remove
 * desktop-only probes that must not leak into an iPhoneOS translation unit.
 * Juice's Wine sources already contain their own iPhoneOS guards for cdrom,
 * device constants, Mach task-port code, power APIs, loader and virtual memory.
 */
#undef HAVE_SYS_USER_H
#undef HAVE_SYS_PTRACE_H
#undef HAVE_NETINET_TCP_FSM_H
#undef HAVE_NETINET_TCP_VAR_H
#undef HAVE_LIBPROCSTAT
#undef HAVE_PROCSTAT_OPEN_SYSCTL

#ifndef WINE_IOS
#define WINE_IOS 1
#endif

#endif
C_EOF

cat > "$GENERATED/winarc_ntdll_exit_isolation.h" <<'C_EOF'
#ifndef WINARC_NTDLL_EXIT_ISOLATION_H
#define WINARC_NTDLL_EXIT_ISOLATION_H

/*
 * Native Wine runs as a process and may call exit(). WinArc hosts Wine in an
 * app-owned pthread, so an ntdll-side fatal exit must never terminate UIKit.
 *
 * Revision 7 only compiles/archives ntdll. The later runtime-link stage will
 * replace this minimal thread exit with the final per-Windows-process unwind
 * boundary.
 */
#include <pthread.h>
#include <stdint.h>

static inline __attribute__((noreturn))
void winarc_ntdll_thread_exit(int status)
{
    pthread_exit((void *)(intptr_t)status);
    __builtin_unreachable();
}

#define exit(status) winarc_ntdll_thread_exit(status)

#endif
C_EOF

SDK="$(xcrun --sdk iphoneos --show-sdk-path)"
CLANG="$(xcrun --sdk iphoneos --find clang)"
AR="$(xcrun --sdk iphoneos --find ar)"
NM="$(xcrun --sdk iphoneos --find nm)"
LIPO="$(xcrun --find lipo)"
IOS_TARGET="arm64-apple-ios$MIN_IOS"

NTDLL_OBJ="$BUILD/ntdll-ios-obj"
NTDLL_ARCHIVE="$BUILD/libWinArcNtdllUnix.a"
NTDLL_NM="$LOGS/ntdll-ios-nm.txt"
NTDLL_UNDEF="$LOGS/ntdll-ios-undefined.txt"

rm -rf "$NTDLL_OBJ"
mkdir -p "$NTDLL_OBJ"

NTDLL_CFLAGS=(
    -target "$IOS_TARGET"
    -arch arm64
    -isysroot "$SDK"
    "-miphoneos-version-min=$MIN_IOS"
    -O2
    -fPIC
    -fno-common
    -fvisibility=hidden
    -fno-stack-protector
    -fno-strict-aliasing
    -D__WINESRC__
    -D_NTSYSTEM_
    -D_ACRTIMP=
    -DWINBASEAPI=
    -DWINE_UNIX_LIB
    -DWINE_IOS=1
    -Dget_thread_context=ntdll_get_thread_context
    -Dset_thread_context=ntdll_set_thread_context
    -DBINDIR=\"/usr/local/bin\"
    -DLIBDIR=\"/usr/local/lib\"
    -DDATADIR=\"/usr/local/share\"
    -DSYSTEMDLLPATH=\"\"
    -I"$GENERATED"
    -I"$HOST_BUILD/dlls/ntdll"
    -I"$WINE/dlls/ntdll"
    -I"$WINE/dlls/ntdll/unix"
    -I"$HOST_BUILD/include"
    -I"$WINE/include"
    -include "$GENERATED/winarc_ntdll_ios_config.h"
    -include "$GENERATED/winarc_ntdll_exit_isolation.h"
    -Wno-deprecated-declarations
    -Wno-implicit-function-declaration
    -Wno-int-conversion
)

NTDLL_SOURCES=()
while IFS= read -r src; do
    NTDLL_SOURCES+=("$src")
done < <(find "$WINE/dlls/ntdll/unix" -maxdepth 1 -type f -name '*.c' | sort)

test "${#NTDLL_SOURCES[@]}" -ge 20 || \
    die "unexpectedly small ntdll Unix source set: ${#NTDLL_SOURCES[@]}"

log "WINE_NTDLL_UNIX_SOURCE_COUNT=${#NTDLL_SOURCES[@]}"

: > "$LOGS/ntdll-ios-objects.txt"

for src in "${NTDLL_SOURCES[@]}"; do
    name="$(basename "$src" .c)"
    obj="$NTDLL_OBJ/$name.o"
    err="$LOGS/ntdll-$name.err"

    log "CC ntdll/unix/$name.c"

    if test "$name" = "virtual"; then
        if ! "$CLANG" "${NTDLL_CFLAGS[@]}" \
            -include "$JUICE_DIR/toolchain/juice-ios-map-tryfixed.h" \
            -c "$src" -o "$obj" 2>"$err"; then
            cat "$err" >&2
            die "iOS ntdll Unix compile failed: $name.c"
        fi
    else
        if ! "$CLANG" "${NTDLL_CFLAGS[@]}" \
            -c "$src" -o "$obj" 2>"$err"; then
            cat "$err" >&2
            die "iOS ntdll Unix compile failed: $name.c"
        fi
    fi

    file "$obj" | grep -q 'Mach-O 64-bit' || \
        die "ntdll object is not Mach-O 64-bit: $name.o"
    file "$obj" | grep -q 'arm64' || \
        die "ntdll object is not ARM64: $name.o"

    printf '%s\n' "$obj" >> "$LOGS/ntdll-ios-objects.txt"
done

log "WINE_NTDLL_UNIX_OBJECT_COMPILE=PASS"

rm -f "$NTDLL_ARCHIVE"
"$AR" rcs "$NTDLL_ARCHIVE" "$NTDLL_OBJ"/*.o

test -s "$NTDLL_ARCHIVE" || die "ntdll Unix static archive was not produced"

"$NM" -g "$NTDLL_ARCHIVE" > "$NTDLL_NM"
"$NM" -u "$NTDLL_ARCHIVE" > "$NTDLL_UNDEF" || true

grep -Fq "__wine_main" "$NTDLL_NM" || \
    die "__wine_main is missing from ntdll Unix archive"

# Avoid the first known same-process collision class before we link server and
# ntdll into the app. These are intentionally renamed through compiler defines.
grep -Fq "ntdll_get_thread_context" "$NTDLL_NM" || \
    die "renamed ntdll_get_thread_context symbol missing"
grep -Fq "ntdll_set_thread_context" "$NTDLL_NM" || \
    die "renamed ntdll_set_thread_context symbol missing"

"$LIPO" -info "$NTDLL_ARCHIVE" | tee "$LOGS/ntdll-ios-lipo.txt"
grep -Eq 'arm64' "$LOGS/ntdll-ios-lipo.txt" || \
    die "ntdll Unix archive does not report ARM64"

log "WINE_NTDLL_WINE_MAIN_SYMBOL=PASS"
log "WINE_NTDLL_CONTEXT_SYMBOL_ISOLATION=PASS"
log "WINE_NTDLL_ARM64_IPHONEOS=PASS"
log "WINE_NTDLL_UNIX_STATIC_ARCHIVE=PASS"

# ---------------------------------------------------------------------------
# Gate 2: record the new boundary.
#
# We deliberately stop before linking the ntdll archive into the existing
# client bridge. The undefined-symbol report from this build tells the next
# revision exactly which Wine-native dependencies must be resolved without
# accidentally pulling desktop/macOS process ownership back into WinArc.
# ---------------------------------------------------------------------------

cat >> "$WINE_ROOT/BASELINE" <<EOF

REVISION7_NTDLL_UNIX_ARCHIVE=libWinArcNtdllUnix.a
REVISION7_NTDLL_UNIX_OBJECT_COMPILE=PASS
REVISION7_NTDLL_WINE_MAIN_SYMBOL=PASS
REVISION7_NTDLL_CONTEXT_SYMBOL_ISOLATION=PASS
REVISION7_NTDLL_ARM64_IPHONEOS=PASS
REVISION7_NTDLL_CLIENT_STATIC_LINK=NOT_YET
REVISION7_NEXT_STAGE=ntdll-client-static-link
EOF

log "WINE_CLIENT_NTDLL_BINARY=STATIC_READY"
log "WINE_NTDLL_CLIENT_STATIC_LINK=NOT_YET"
log "WINARC_NEXT_ENGINEERING_STAGE=NTDLL_CLIENT_STATIC_LINK"

# Preserve the markers already expected by the current workflow. Revision 6
# emitted them after actually rebuilding the verified baseline; these are not
# fabricated replacements for a skipped build.
log "WINARC_WINE_BOOTSTRAP=PASS"
